#!/usr/bin/env node
/**
 * Vendors KaTeX into webview-ui/lib/ as fully self-contained assets:
 *
 *   webview-ui/lib/katex.min.js     — verbatim from the katex npm package
 *   webview-ui/lib/katex-inline.css — katex.min.css with every @font-face
 *                                     reduced to its woff2 source embedded
 *                                     as a base64 data: URI
 *
 * Webviews must not load assets via asWebviewUri (service workers are
 * unreliable in Firefox/Safari under code-server, see issue #267/#274), so
 * fonts have to travel inside the inlined stylesheet. The webview CSP
 * allows this via `font-src ... data:`.
 *
 * Usage: npm run vendor:katex   (outputs are committed; re-run to upgrade)
 */
const { execSync } = require('child_process');
const fs = require('fs');
const os = require('os');
const path = require('path');

const KATEX_VERSION = '0.16.22';

const repoRoot = path.resolve(__dirname, '..');
const outDir = path.join(repoRoot, 'webview-ui', 'lib');

function fail(msg) {
  console.error(`vendor-katex: ${msg}`);
  process.exit(1);
}

const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'vendor-katex-'));
try {
  console.log(`Fetching katex@${KATEX_VERSION} ...`);
  const tarball = execSync(`npm pack katex@${KATEX_VERSION} --silent`, {
    cwd: tmpDir,
    encoding: 'utf8',
  })
    .trim()
    .split('\n')
    .pop();
  execSync(`tar -xzf ${JSON.stringify(tarball)}`, { cwd: tmpDir });

  const dist = path.join(tmpDir, 'package', 'dist');
  const js = fs.readFileSync(path.join(dist, 'katex.min.js'), 'utf8');
  let css = fs.readFileSync(path.join(dist, 'katex.min.css'), 'utf8');

  // Reduce each @font-face src list to a single embedded woff2 entry.
  // katex.min.css declares src:url(fonts/X.woff2) format("woff2"),url(...woff)...,url(...ttf)...
  let embedded = 0;
  css = css.replace(
    /src:\s*url\(fonts\/([^)]+\.woff2)\)\s*format\(["']woff2["']\)[^;}]*/g,
    (_match, fontFile) => {
      const fontPath = path.join(dist, 'fonts', fontFile);
      if (!fs.existsSync(fontPath)) fail(`font file missing in package: ${fontFile}`);
      const b64 = fs.readFileSync(fontPath).toString('base64');
      embedded += 1;
      return `src:url(data:font/woff2;base64,${b64}) format("woff2")`;
    }
  );

  if (embedded === 0) fail('no @font-face src entries matched — katex.min.css layout changed');
  if (/url\(fonts\//.test(css)) fail('residual url(fonts/...) reference survived the transform');
  if (/<\/style/i.test(css)) fail('generated CSS contains "</style" — unsafe to inline');

  const header = (file) =>
    `/* GENERATED by scripts/vendor-katex.js — katex v${KATEX_VERSION} (${file}). ` +
    `Do not edit; regenerate with: npm run vendor:katex */\n`;

  fs.writeFileSync(path.join(outDir, 'katex.min.js'), header('katex.min.js') + js);
  fs.writeFileSync(path.join(outDir, 'katex-inline.css'), header('katex.min.css + embedded woff2 fonts') + css);

  const kb = (f) => Math.round(fs.statSync(path.join(outDir, f)).size / 1024);
  console.log(`Wrote webview-ui/lib/katex.min.js (${kb('katex.min.js')} KB)`);
  console.log(`Wrote webview-ui/lib/katex-inline.css (${kb('katex-inline.css')} KB, ${embedded} fonts embedded)`);
} finally {
  fs.rmSync(tmpDir, { recursive: true, force: true });
}
